### ISSUE TITLE
Use custom commands in other servers

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/discord-bot#103]
Though some custom commands are only relevant to the WOM server, it would be helpful to be able to allow some custom commands to be used outside of the wise old man server. To keep it easy to edit the custom commands, I suggest adding something like the bottom line here:
```
command: "runelite",
message: "Enabling the XP Updater plugin on Runelite is an easy, reliable way to keep your Wise Old Man profile up to date."
image: "https://imgur.com/tv0Jro8”
type: public
```

This would hopefully keep it easy to change/add for mods even if they don’t have much coding experience (like me)

**Comment by psikoi** [comment]
Implemented in #108
