### ISSUE TITLE
Allow capitalisation in commands

### ISSUE THREAD

**Issue by BoomOSRS** [wise-old-man/discord-bot#109]
In the example below !group hiscores zulrah worked. !group hiscores Zulrah didn't.
Interestingly it appears to have the players in the right order, but all with 0kc and an invalid metric name in the title.

![image](https://user-images.githubusercontent.com/70453840/126185072-4bd963db-fa61-443a-a709-838b1e94e65e.png)

**Comment by psikoi** [comment]
Nvm re-opening, still occurs.

It now displays the kc values correctly. but fails to display the metric's name and icon on the embed title.

![image](https://user-images.githubusercontent.com/3278148/135764548-286fe5cf-30fc-4246-a221-26878e75beac.png)
