### ISSUE TITLE
Bot command for capitalization

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/discord-bot#112]
As a workaround for name capitalization, we should add a command, similar to !setflag, to set capitilization for usernames. A command example would be:

`!setcaps {userID / username} {CAPITALIZED NAME}`

So for me:

`!setcaps 1709 SeThMaRe`

**This would only be useable in a specified channel to help moderate these changes.**

If we decide that this action requires admin approval (which might not be necessary), maybe we could add reactions to the bot's response that only admin/mods/etc. can use to approve/reject capitalization (checkmark to approve, X to reject)?

**Comment by psikoi** [comment]
Our current name changes system allows (and auto-approved) capitalisation changes, we don't need this anymore, closing 👋
