### ISSUE TITLE
Gained tab on website not sorting users alphabetically

### ISSUE THREAD

**Issue by ghost** [wise-old-man/discord-bot#126]
Our clan gives points to users depending how much exp they got each week.
Whilst checking it, I've noticed you can sort the list by column headers (rank,start,end,gained) except name.
I was wondering if this was intended that you can't sort names alphabetically or if it's a bug.
![Screenshot_342](https://user-images.githubusercontent.com/38259739/138561259-ea511682-2b6c-4117-bfb6-af937bb42652.png)
It would make tracking users gained exp and giving points for them a lot quicker if we could sort names alphabetically, if this were to be resolved.
Thank you for your consideration

**Comment by psikoi** [comment]
this was fixed, and also this is the discord bot's repository, so the issue doesn't apply here.
