### ISSUE TITLE
Enable strictNullChecks in the tsconfig

### ISSUE THREAD

**Issue by aleccaputo** [wise-old-man/discord-bot#178]
`"strictNullChecks": true,` should be enabled in the tsconfig. By enabling it it will give us proper typechecking (ie string 
 null inferring as such instead of just string). This will come with a fair amount of fixes to the existing code to fix null checks
 
 https://www.typescriptlang.org/tsconfig#strictNullChecks

**Comment by psikoi** [comment]
Done in #179
