### ISSUE TITLE
Duration for competition announcement

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/discord-bot#32]
![image](https://user-images.githubusercontent.com/66145237/92551463-43937f00-f21b-11ea-9a31-f3f5a5bebdf1.jpeg)
I have a month long competition scheduled to start in about a week. When it was announced in Discord, the duration said undefined even though i did set a duration.
![image](https://user-images.githubusercontent.com/66145237/92551499-632aa780-f21b-11ea-82ad-917efaa69bfb.jpeg)

**Comment by psikoi** [comment]
Duplicate of https://github.com/wise-old-man/wise-old-man/issues/294.

Quick fix, i'll try tonight

**Comment by Sethmare** [comment]
Related note:
Start date is showing the end date when doing !group competitions --upcoming
![Screenshot_39](https://user-images.githubusercontent.com/66145237/92825819-34ccd980-f38d-11ea-8908-a8ae2ccd76be.png)

**Comment by psikoi** [comment]
https://github.com/wise-old-man/discord-bot/blob/master/src/commands/instances/group/GroupCompetition.ts

Line 60: should be `startsAt` instead of `endsAt`

**Comment by psikoi** [comment]
Both fixed.
