### ISSUE TITLE
Auto-update instructions

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/discord-bot#38]
This one should be pretty simple, it might be helpful to create a command that instructs users on how to set up RuneLite XP updater. This would make it easier for us to show people how to do it. Maybe an imbeded screenshot or gif or something.

**Comment by psikoi** [comment]
I like this, besides adding a new command, we could also make it so whenever a `!update` command is ran on an outdated player (let's say no updates in the past week), we would add a ⚠️ message saying "hey! try the !runelite command and such and such"

This could help users discover this new command.

**Comment by psikoi** [comment]
Is this still needed @Sethmare ?

**Comment by Sethmare** [comment]
We have the ability to do custom command with images now, which is awesome. However it would probably be a cool idea to toggle which custom commands can be used outside of the WOM server so we can use these in other places.

Also, did you still want to do something like this?
>we could also make it so whenever a !update command is ran on an outdated player (let's say no updates in the past week), we would add a ⚠️ message saying "hey! try the !runelite command and such and such"

**Comment by Sethmare** [comment]
Should be fixed with #108

**Comment by psikoi** [comment]
> Should be fixed with #108

oops yes, missed this comment at the time
