### ISSUE TITLE
Bugs when using the mobile website. 

### ISSUE THREAD

**Issue by jossie9** [wise-old-man/discord-bot#73]
Hi!

First of all I would like to say I really like the website, it’s amazing! 
I found 3 bugs on the website and have 1 small suggestion. 
All bugs are found on iOS using Safari (have not checked other webbrowsers). 

1: When looking at the overview on mobile, the dates underneath the graph overlap. 
![BFF68715-3BCF-4D8D-993C-6992BC1B150D](https://user-images.githubusercontent.com/21177987/109455161-01a60180-7a24-11eb-8f88-e3dc12606926.png)

2: When selecting a custom time range, the lowest row of dates can’t be tapped on.
![DC75C65C-2F90-485D-A4A8-25AB127DDFD7](https://user-images.githubusercontent.com/21177987/109455166-04085b80-7a24-11eb-8045-a75c6c8c899f.png)

3: When opening the menu from the top right corner, the lowest 1-2 menu items can’t be tapped on. 
![383A25B3-27D7-47C5-B729-F17A26D28B80](https://user-images.githubusercontent.com/21177987/109455171-05d21f00-7a24-11eb-9541-229a5975aaec.png)

(4: I would suggest switching the graphs with the gained exp. So the graphs are at the bottom.)

**Comment by psikoi** [comment]
Nice. The first one might be annoying to fix as I'm using a third party library, everything else seems alright.

The mobile menu is supposed to be scrollable, is it not? (3)

**Comment by jossie9** [comment]
Hi! Thank you for the fast response! 
the menu is scrollable, but the lowest button is at the spot where the Safari menu buttons are. 
I recorded my screen to show you. 

https://user-images.githubusercontent.com/21177987/109509597-0b088b80-7a6f-11eb-83db-a500c1c9459e.MP4

**Comment by Sethmare** [comment]
I had the same issue, but then I discovered you can hide the toolbar. However, not everybody will know how to do that so it is still worth trying to find a solution.

![048F5963-B49A-416C-B559-7CF9E902AD56](https://user-images.githubusercontent.com/66145237/109510112-de4c7800-7a5e-11eb-9d35-bcd528642487.png)

**Comment by jossie9** [comment]
Thank you for this little workaround! 
I am a longtime Apple user/nerd, but I didn’t know about that button 😱
It is a workaround for now.
