### ISSUE TITLE
Configuration help

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/discord-bot#78]
I think it would be more user friendly to add some kind of help for the !config command. The current wom!help command has a lot of elements I would imagine in this command, but I think !config could afford to bring up more details.

Showing the set channel for each type of announcement would help give a brief overview to admins, and would probably help somebody less familiar with the bot to know the proper language to use the command.

Example of what to show

Prefix
Group name and/or id
Number of members
Channel:default (channelname)
Channel:competition-status (channelname or “default” if set to default)
Etc.

It doesn’t have to be exactly like this, but i think something like this would improve the user experience

**Comment by psikoi** [comment]
I think this was improved by the slash commands update, also we no longer have configs for prefixes, so it's only "config group" or "config notifications". closing 👋
