### ISSUE TITLE
Mentioning the bot

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/discord-bot#79]
This suggestion is two parts:

**1-** When you mention `@Wise Old Man`, send a message showing the server's prefix. This is helpful for people wanting to use the bot on an unfamiliar server, or for somebody who forgot what the set prefix was.

**2-** Treat mentions of `@Wise Old Man` as if the prefix was being used. In addition to being useful for the same reasons as the first suggestion, this can help users interact with the intended bot when multiple bots use the same prefix. **Ex.** `@Wise Old Man help` would be the same as `wom!help`, and `@Wise Old Man gained` would be the same as `!gained`.

**Comment by psikoi** [comment]
Does not apply anymore, the bot now only works using slash commands
